//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("3.0.2")]
[assembly: AssemblyFileVersion("3.0.2")]
[assembly: AssemblyInformationalVersion("3.0.2-alpha.16+Branch.develop.Sha.74f55351d77ec5a0739008c0d4b2a028e5444766")]

